CREATE TABLE baninst1.ZSTULPR
(
  ZSTULPR_ID                 INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
  ZSTULPR_PIDM               NUMBER (8) NOT NULL,
  ZSTULPR_STATE_CODE         VARCHAR2 (3 CHAR),
  ZSTULPR_AKNOWLEDGE_DATE    DATE DEFAULT SYSDATE,
  PRIMARY KEY (ZSTULPR_ID)
);

ALTER TABLE baninst1.ZSTULPR
  ADD (
    CONSTRAINT FK1_ZSTULPR_STVSTAT_CODE FOREIGN KEY (ZSTULPR_STATE_CODE)
      REFERENCES SATURN.STVSTAT (STVSTAT_CODE)
      ENABLE VALIDATE);
