--sqlplus dbeu_owner/password
SET SERVEROUTPUT ON
DROP TRIGGER BANINST1.GT_ZSALOCA_SURROGATE_ID;
DROP PUBLIC SYNONYM ZSALOCA_SURROGATE_ID_SEQUENCE;
DROP SEQUENCE BANINST1.ZSALOCA_SURROGATE_ID_SEQUENCE;
EXECUTE dbeu_util.teardown_table('BANINST1','ZSALOCA');
EXECUTE dbeu_util.process_table('BANINST1','ZSALOCA');
EXECUTE dbeu_util.apply_table('BANINST1','ZSALOCA');
EXECUTE dbeu_util.extend_table('BANINST1','ZSALOCA','F',TRUE);